In [1]:
import pandas as pd
import numpy as np

In [2]:
#1.read the csv file
df=pd.read_csv("diabetes1.csv")
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [ ]:
#2.Doing Basic Checks

In [3]:
df.shape

(768, 9)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [5]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [9]:
#3.select numeric columns
df.select_dtypes(include=['int','float'])

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [12]:
#4.rename the columm
df.rename({'Outcome':'result'},axis=1,inplace=True)

In [13]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,result
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [14]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
result                      0
dtype: int64

In [16]:
df['Glucose']=df['Glucose'].replace(0,df['Glucose'].mean())

In [22]:
columns=df.loc[:,['Glucose','BloodPressure','Insulin','BMI']]

In [23]:
columns

     Glucose  BloodPressure  Insulin   BMI
0      148.0             72        0  33.6
1       85.0             66        0  26.6
2      183.0             64        0  23.3
3       89.0             66       94  28.1
4      137.0             40      168  43.1
..       ...            ...      ...   ...
763    101.0             76      180  32.9
764    122.0             70        0  36.8
765    121.0             72      112  26.2
766    126.0             60        0  30.1
767     93.0             70        0  30.4

[768 rows x 4 columns]

In [24]:
for i in columns:
    df[i]=df[i].replace(0,df[i].mean())

In [25]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,result
0,6,148.0,72.0,35,79.799479,33.6,0.627,50,1
1,1,85.0,66.0,29,79.799479,26.6,0.351,31,0
2,8,183.0,64.0,0,79.799479,23.3,0.672,32,1
3,1,89.0,66.0,23,94.000000,28.1,0.167,21,0
4,0,137.0,40.0,35,168.000000,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48,180.000000,32.9,0.171,63,0
764,2,122.0,70.0,27,79.799479,36.8,0.340,27,0
765,5,121.0,72.0,23,112.000000,26.2,0.245,30,0
766,1,126.0,60.0,0,79.799479,30.1,0.349,47,1
767,1,93.0,70.0,31,79.799479,30.4,0.315,23,0

In [27]:
columns1=['Glucose','BMI','Insulin','BloodPressure']

In [29]:
for i in columns:
	df[i]=df[i].replace(0,df[i].mean())

In [30]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,result
0,6,148.0,72.0,35,79.799479,33.6,0.627,50,1
1,1,85.0,66.0,29,79.799479,26.6,0.351,31,0
2,8,183.0,64.0,0,79.799479,23.3,0.672,32,1
3,1,89.0,66.0,23,94.000000,28.1,0.167,21,0
4,0,137.0,40.0,35,168.000000,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48,180.000000,32.9,0.171,63,0
764,2,122.0,70.0,27,79.799479,36.8,0.340,27,0
765,5,121.0,72.0,23,112.000000,26.2,0.245,30,0
766,1,126.0,60.0,0,79.799479,30.1,0.349,47,1
767,1,93.0,70.0,31,79.799479,30.4,0.315,23,0

In [34]:
df[(df['Age']>50)&(df['Age']<=70)].shape[0]

79

In [37]:
df[(df['Age']>40)&(df['Age']<=50)&(df['result']==1)]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,result
0,6,148.0,72.0,35,79.799479,33.6,0.627,50,1
22,7,196.0,90.0,0,79.799479,39.8,0.451,41,1
25,10,125.0,70.0,26,115.000000,31.1,0.205,41,1
26,7,147.0,76.0,0,79.799479,39.4,0.257,43,1
37,9,102.0,76.0,37,79.799479,32.9,0.665,46,1
...,...,...,...,...,...,...,...,...,...
743,9,140.0,94.0,0,79.799479,32.7,0.734,45,1
749,6,162.0,62.0,0,79.799479,24.3,0.178,50,1
754,8,154.0,78.0,32,79.799479,32.4,0.443,45,1
761,9,170.0,74.0,31,79.799479,44.0,0.403,43,1
766,1,126.0,60.0,0,79.799479,30.1,0.349,47,1

In [41]:
df.drop('Insulin',axis=1)

,Pregnancies,Glucose,BloodPressure,SkinThickness,BMI,DiabetesPedigreeFunction,Age,result
0,6,148.0,72.0,35,33.6,0.627,50,1
1,1,85.0,66.0,29,26.6,0.351,31,0
2,8,183.0,64.0,0,23.3,0.672,32,1
3,1,89.0,66.0,23,28.1,0.167,21,0
4,0,137.0,40.0,35,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48,32.9,0.171,63,0
764,2,122.0,70.0,27,36.8,0.340,27,0
765,5,121.0,72.0,23,26.2,0.245,30,0
766,1,126.0,60.0,0,30.1,0.349,47,1
767,1,93.0,70.0,31,30.4,0.315,23,0

In [45]:
g=df.groupby('result')
g

In [46]:
list(g)

[(0,
       Pregnancies  Glucose  BloodPressure  SkinThickness     Insulin   BMI  \
  1              1     85.0      66.000000             29   79.799479  26.6
  3              1     89.0      66.000000             23   94.000000  28.1
  5              5    116.0      74.000000              0   79.799479  25.6
  7             10    115.0      69.105469              0   79.799479  35.3
  10             4    110.0      92.000000              0   79.799479  37.6
  ..           ...      ...            ...            ...         ...   ...
  762            9     89.0      62.000000              0   79.799479  22.5
  763           10    101.0      76.000000             48  180.000000  32.9
  764            2    122.0      70.000000             27   79.799479  36.8
  765            5    121.0      72.000000             23  112.000000  26.2
  767            1     93.0      70.000000             31   79.799479  30.4

       DiabetesPedigreeFunction  Age  result
  1                       0.351   31       0
  3                       0.167   21       0
  5                       0.201   30       0
  7                       0.134   29       0
  10                      0.191   30       0
  ..                        ...  ...     ...
  762                     0.142   33       0
  763                     0.171   63       0
  764                     0.340   27       0
  765                     0.245   30       0
  767                     0.315   23       0

  [500 rows x 9 columns]),
 (1,
       Pregnancies  Glucose  BloodPressure  SkinThickness     Insulin   BMI  \
  0              6    148.0           72.0             35   79.799479  33.6
  2              8    183.0           64.0              0   79.799479  23.3
  4              0    137.0           40.0             35  168.000000  43.1
  6              3     78.0           50.0             32   88.000000  31.0
  8              2    197.0           70.0             45  543.000000  30.5
  ..           ...      ...            ...            ...         ...   ...
  755            1    128.0           88.0             39  110.000000  36.5
  757            0    123.0           72.0              0   79.799479  36.3
  759            6    190.0           92.0              0   79.799479  35.5
  761            9    170.0           74.0             31   79.799479  44.0
  766            1    126.0           60.0              0   79.799479  30.1

       DiabetesPedigreeFunction  Age  result
  0                       0.627   50       1
  2                       0.672   32       1
  4                       2.288   33       1
  6                       0.248   26       1
  8                       0.158   53       1
  ..                        ...  ...     ...
  755                     1.057   37       1
  757                     0.258   52       1
  759                     0.278   66       1
  761                     0.403   43       1
  766                     0.349   47       1

  [268 rows x 9 columns])]

In [74]:
for key, group in df.groupby('result')[['Pregnancies','BMI']]:
    print(key)
    print(group)

1
     Pregnancies   BMI
0              6  33.6
2              8  23.3
4              0  43.1
6              3  31.0
8              2  30.5
..           ...   ...
755            1  36.5
757            0  36.3
759            6  35.5
761            9  44.0
766            1  30.1

[268 rows x 2 columns]

In [75]:
df.groupby(['result', 'Age']).count()

            Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  BMI  \
result Age
1      21             5        5              5              5        5    5
       22            11       11             11             11       11   11
       23             7        7              7              7        7    7
       24             8        8              8              8        8    8
       25            14       14             14             14       14   14
       26             8        8              8              8        8    8
       27             8        8              8              8        8    8
       28            10       10             10             10       10   10
       29            13       13             13             13       13   13
       30             6        6              6              6        6    6
       31            13       13             13             13       13   13
       32             9        9              9              9        9    9
       33            10       10             10             10       10   10
       34             4        4              4              4        4    4
       35             5        5              5              5        5    5
       36            10       10             10             10       10   10
       37             6        6              6              6        6    6
       38            10       10             10             10       10   10
       39             3        3              3              3        3    3
       40             6        6              6              6        6    6
       41            13       13             13             13       13   13
       42             7        7              7              7        7    7
       43            11       11             11             11       11   11
       44             5        5              5              5        5    5
       45             8        8              8              8        8    8
       46             7        7              7              7        7    7
       47             4        4              4              4        4    4
       48             1        1              1              1        1    1
       49             3        3              3              3        3    3
       50             5        5              5              5        5    5
       51             5        5              5              5        5    5
       52             7        7              7              7        7    7
       53             4        4              4              4        4    4
       54             4        4              4              4        4    4
       55             1        1              1              1        1    1
       56             2        2              2              2        2    2
       57             1        1              1              1        1    1
       58             3        3              3              3        3    3
       59             2        2              2              2        2    2
       60             2        2              2              2        2    2
       61             1        1              1              1        1    1
       62             2        2              2              2        2    2
       66             2        2              2              2        2    2
       67             1        1              1              1        1    1
       70             1        1              1              1        1    1

            DiabetesPedigreeFunction
result Age
1      21                          5
       22                         11
       23                          7
       24                          8
       25                         14
       26                          8
       27                          8
       28                         10
       29                         13
       30                          6
       31                         13
       32                          9
       33                         10
       34                          4
       35                          5
       36                         10
       37                          6
       38                         10
       39                          3
       40                          6
       41                         13
       42                          7
       43                         11
       44                          5
       45                          8
       46                          7
       47                          4
       48                          1
       49                          3
       50                          5
       51                          5
       52                          7
       53                          4
       54                          4
       55                          1
       56                          2
       57                          1
       58                          3
       59                          2
       60                          2
       61                          1
       62                          2
       66                          2
       67                          1
       70                          1

In [76]:
df.groupby('result')['Age'].agg(['mean', 'max', 'count', 'min'])

             mean  max  count  min
result
1       37.067164   70    268   21

In [77]:
df['result'].unique()

array([1], dtype=int64)

In [81]:
def categorize_bmi(BMI):
    if BMI < 18:
        return 'underweight'
    elif 18 <= BMI <= 25:
        return 'fit'
    else:
        return 'overweight'

In [88]:
df['bmi_category'] = df['BMI'].apply(categorize_bmi)
print("Data with new 'bmi_category' column:")
print(df[['BMI', 'bmi_category']].head())

Data with new 'bmi_category' column:
    BMI bmi_category
0  33.6   overweight
2  23.3          fit
4  43.1   overweight
6  31.0   overweight
8  30.5   overweight