In [1]:
#read weather data
import pandas as pd
wea=pd.read_csv('wea.csv')
wea

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
1    1/2/2017   NaN   NaN       NaN
2    1/3/2017  35.0   7.0     Sunny
3    1/4/2017   NaN   NaN       NaN
4    1/5/2017   NaN   NaN       NaN
5    1/6/2017  28.0   2.0      Snow
6    1/7/2017   NaN   NaN       NaN
7    1/8/2017   NaN   5.0      Rain
8    1/9/2017   NaN   NaN       NaN
9   1/10/2017  24.0   7.0      Snow
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

In [4]:
wea.isnull().sum().sum()

16

In [2]:
#DATA INSPECTION:
#head
wea.head(8)

        day  temp  wind condition
0  1/1/2017  32.0   6.0      Rain
1  1/2/2017   NaN   NaN       NaN
2  1/3/2017  35.0   7.0     Sunny
3  1/4/2017   NaN   NaN       NaN
4  1/5/2017   NaN   NaN       NaN
5  1/6/2017  28.0   2.0      Snow
6  1/7/2017   NaN   NaN       NaN
7  1/8/2017   NaN   5.0      Rain

In [3]:
wea.tail()

          day  temp  wind condition
7    1/8/2017   NaN   5.0      Rain
8    1/9/2017   NaN   NaN       NaN
9   1/10/2017  24.0   7.0      Snow
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

In [4]:
wea.sample(5)

          day  temp  wind condition
8    1/9/2017   NaN   NaN       NaN
10  1/11/2017  32.0   4.0      Rain
6    1/7/2017   NaN   NaN       NaN
3    1/4/2017   NaN   NaN       NaN
1    1/2/2017   NaN   NaN       NaN

In [24]:
wea.shape

(12, 4)

In [6]:
wea.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   day        12 non-null     object
 1   temp       6 non-null      float64
 2   wind       7 non-null      float64
 3   condition  7 non-null      object
dtypes: float64(2), object(2)
memory usage: 516.0+ bytes

In [7]:
wea.describe(include='O')

             day condition
count         12         7
unique        12         3
top     1/1/2017      Rain
freq           1         3

In [8]:
#data selection(basic)
wea[['temp','condition','day']]

    temp condition        day
0   32.0      Rain   1/1/2017
1    NaN       NaN   1/2/2017
2   35.0     Sunny   1/3/2017
3    NaN       NaN   1/4/2017
4    NaN       NaN   1/5/2017
5   28.0      Snow   1/6/2017
6    NaN       NaN   1/7/2017
7    NaN      Rain   1/8/2017
8    NaN       NaN   1/9/2017
9   24.0      Snow  1/10/2017
10  32.0      Rain  1/11/2017
11  31.0     Sunny  1/12/2017

In [28]:
wea.isnull().sum()

day          0
temp         6
wind         5
condition    5
dtype: int64

#### To fill null values -fillna()
##### 1.1 by value
##### 1.2 ffill
##### 1.3 bfill
##### 1.4 using Dict

In [9]:
wea.fillna(5)

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
1    1/2/2017   5.0   5.0         5
2    1/3/2017  35.0   7.0     Sunny
3    1/4/2017   5.0   5.0         5
4    1/5/2017   5.0   5.0         5
5    1/6/2017  28.0   2.0      Snow
6    1/7/2017   5.0   5.0         5
7    1/8/2017   5.0   5.0      Rain
8    1/9/2017   5.0   5.0         5
9   1/10/2017  24.0   7.0      Snow
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

In [10]:
wea

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
1    1/2/2017   NaN   NaN       NaN
2    1/3/2017  35.0   7.0     Sunny
3    1/4/2017   NaN   NaN       NaN
4    1/5/2017   NaN   NaN       NaN
5    1/6/2017  28.0   2.0      Snow
6    1/7/2017   NaN   NaN       NaN
7    1/8/2017   NaN   5.0      Rain
8    1/9/2017   NaN   NaN       NaN
9   1/10/2017  24.0   7.0      Snow
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

In [29]:
wea.fillna(method='ffill',limit=1)

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
1    1/2/2017  32.0   6.0      Rain
2    1/3/2017  35.0   7.0     Sunny
3    1/4/2017  35.0   7.0     Sunny
4    1/5/2017  35.0   7.0     Sunny
5    1/6/2017  28.0   2.0      Snow
6    1/7/2017  28.0   2.0      Snow
7    1/8/2017  28.0   5.0      Rain
8    1/9/2017  28.0   5.0      Rain
9   1/10/2017  24.0   7.0      Snow
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

In [12]:
wea.fillna(method='bfill',limit=1)

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
1    1/2/2017  35.0   7.0     Sunny
2    1/3/2017  35.0   7.0     Sunny
3    1/4/2017   NaN   NaN       NaN
4    1/5/2017  28.0   2.0      Snow
5    1/6/2017  28.0   2.0      Snow
6    1/7/2017   NaN   5.0      Rain
7    1/8/2017   NaN   5.0      Rain
8    1/9/2017  24.0   7.0      Snow
9   1/10/2017  24.0   7.0      Snow
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

In [13]:
wea.fillna({'temp':23,'wind':8,'condition':'no event'})

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
1    1/2/2017  23.0   8.0  no event
2    1/3/2017  35.0   7.0     Sunny
3    1/4/2017  23.0   8.0  no event
4    1/5/2017  23.0   8.0  no event
5    1/6/2017  28.0   2.0      Snow
6    1/7/2017  23.0   8.0  no event
7    1/8/2017  23.0   5.0      Rain
8    1/9/2017  23.0   8.0  no event
9   1/10/2017  24.0   7.0      Snow
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

In [14]:
#replace--> df.replace(value to be replaced,with what value)
wea

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
1    1/2/2017   NaN   NaN       NaN
2    1/3/2017  35.0   7.0     Sunny
3    1/4/2017   NaN   NaN       NaN
4    1/5/2017   NaN   NaN       NaN
5    1/6/2017  28.0   2.0      Snow
6    1/7/2017   NaN   NaN       NaN
7    1/8/2017   NaN   5.0      Rain
8    1/9/2017   NaN   NaN       NaN
9   1/10/2017  24.0   7.0      Snow
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

In [15]:
import numpy as np
wea.replace(np.NaN,5)

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
1    1/2/2017   5.0   5.0         5
2    1/3/2017  35.0   7.0     Sunny
3    1/4/2017   5.0   5.0         5
4    1/5/2017   5.0   5.0         5
5    1/6/2017  28.0   2.0      Snow
6    1/7/2017   5.0   5.0         5
7    1/8/2017   5.0   5.0      Rain
8    1/9/2017   5.0   5.0         5
9   1/10/2017  24.0   7.0      Snow
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

In [16]:
wea.replace([np.NaN,'Snow'],[85,'Snows'])

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
1    1/2/2017  85.0  85.0        85
2    1/3/2017  35.0   7.0     Sunny
3    1/4/2017  85.0  85.0        85
4    1/5/2017  85.0  85.0        85
5    1/6/2017  28.0   2.0     Snows
6    1/7/2017  85.0  85.0        85
7    1/8/2017  85.0   5.0      Rain
8    1/9/2017  85.0  85.0        85
9   1/10/2017  24.0   7.0     Snows
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

In [30]:
wea.duplicated().sum()

0

In [ ]:
#wea.drop_duplicates(inplace=True)

In [31]:
wea

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
1    1/2/2017   NaN   NaN       NaN
2    1/3/2017  35.0   7.0     Sunny
3    1/4/2017   NaN   NaN       NaN
4    1/5/2017   NaN   NaN       NaN
5    1/6/2017  28.0   2.0      Snow
6    1/7/2017   NaN   NaN       NaN
7    1/8/2017   NaN   5.0      Rain
8    1/9/2017   NaN   NaN       NaN
9   1/10/2017  24.0   7.0      Snow
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

In [12]:
wea.dropna(thresh=4)

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
2    1/3/2017  35.0   7.0     Sunny
5    1/6/2017  28.0   2.0      Snow
9   1/10/2017  24.0   7.0      Snow
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

In [18]:
#how
#any-delete if there is one null value
#all- delete if all columns are null
#thresh
# thresh=n: It specifies that a row or column must have at least n non-NaN values to be kept. 
# If it has fewer than n non-NaN values, it will be dropped.

In [19]:
wea.dropna(thresh=4)

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
2    1/3/2017  35.0   7.0     Sunny
5    1/6/2017  28.0   2.0      Snow
9   1/10/2017  24.0   7.0      Snow
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

In [20]:
wea.rename(columns={'day':'temperature'},inplace=True)
wea

   temperature  temp  wind condition
0     1/1/2017  32.0   6.0      Rain
1     1/2/2017   NaN   NaN       NaN
2     1/3/2017  35.0   7.0     Sunny
3     1/4/2017   NaN   NaN       NaN
4     1/5/2017   NaN   NaN       NaN
5     1/6/2017  28.0   2.0      Snow
6     1/7/2017   NaN   NaN       NaN
7     1/8/2017   NaN   5.0      Rain
8     1/9/2017   NaN   NaN       NaN
9    1/10/2017  24.0   7.0      Snow
10   1/11/2017  32.0   4.0      Rain
11   1/12/2017  31.0   2.0     Sunny

In [21]:
wea.drop(columns='condition',axis=1,inplace=True)

In [22]:
wea

   temperature  temp  wind
0     1/1/2017  32.0   6.0
1     1/2/2017   NaN   NaN
2     1/3/2017  35.0   7.0
3     1/4/2017   NaN   NaN
4     1/5/2017   NaN   NaN
5     1/6/2017  28.0   2.0
6     1/7/2017   NaN   NaN
7     1/8/2017   NaN   5.0
8     1/9/2017   NaN   NaN
9    1/10/2017  24.0   7.0
10   1/11/2017  32.0   4.0
11   1/12/2017  31.0   2.0