In [1]:
import pandas as pd

In [2]:
weather=pd.read_csv('wea.csv')
weather

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
1    1/2/2017   NaN   NaN       NaN
2    1/3/2017  35.0   7.0     Sunny
3    1/4/2017   NaN   NaN       NaN
4    1/5/2017   NaN   NaN       NaN
5    1/6/2017  28.0   2.0      Snow
6    1/7/2017   NaN   NaN       NaN
7    1/8/2017   NaN   5.0      Rain
8    1/9/2017   NaN   NaN       NaN
9   1/10/2017  24.0   7.0      Snow
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

## Data Cleaning

In [4]:
#nan-(missing value)
weather.isnull()

      day   temp   wind  condition
0   False  False  False      False
1   False   True   True       True
2   False  False  False      False
3   False   True   True       True
4   False   True   True       True
5   False  False  False      False
6   False   True   True       True
7   False   True  False      False
8   False   True   True       True
9   False  False  False      False
10  False  False  False      False
11  False  False  False      False

In [5]:
weather.isnull().sum()

day          0
temp         6
wind         5
condition    5
dtype: int64

In [6]:
weather.isnull().sum().sum()

16

In [ ]:
#1.filling the null values- fillna() methods inside are:
>by value()
>ffill - forward fill
>bfill-backward fill
>using dict

In [8]:
weather.fillna(5)

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
1    1/2/2017   5.0   5.0         5
2    1/3/2017  35.0   7.0     Sunny
3    1/4/2017   5.0   5.0         5
4    1/5/2017   5.0   5.0         5
5    1/6/2017  28.0   2.0      Snow
6    1/7/2017   5.0   5.0         5
7    1/8/2017   5.0   5.0      Rain
8    1/9/2017   5.0   5.0         5
9   1/10/2017  24.0   7.0      Snow
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

In [9]:
weather.fillna(method='ffill')

C:\Users\rmrar\AppData\Local\Temp\ipykernel_32088\589542080.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  weather.fillna(method='ffill')

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
1    1/2/2017  32.0   6.0      Rain
2    1/3/2017  35.0   7.0     Sunny
3    1/4/2017  35.0   7.0     Sunny
4    1/5/2017  35.0   7.0     Sunny
5    1/6/2017  28.0   2.0      Snow
6    1/7/2017  28.0   2.0      Snow
7    1/8/2017  28.0   5.0      Rain
8    1/9/2017  28.0   5.0      Rain
9   1/10/2017  24.0   7.0      Snow
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

In [10]:
#to provide condition such that it will not take multiple values in ffill (if first valus is null value we cannot fill with those value)
weather.fillna(method='ffill',limit=1)

C:\Users\rmrar\AppData\Local\Temp\ipykernel_32088\3978877121.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  weather.fillna(method='ffill',limit=1)

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
1    1/2/2017  32.0   6.0      Rain
2    1/3/2017  35.0   7.0     Sunny
3    1/4/2017  35.0   7.0     Sunny
4    1/5/2017   NaN   NaN       NaN
5    1/6/2017  28.0   2.0      Snow
6    1/7/2017  28.0   2.0      Snow
7    1/8/2017   NaN   5.0      Rain
8    1/9/2017   NaN   5.0      Rain
9   1/10/2017  24.0   7.0      Snow
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

In [11]:
weather.fillna(method='bfill')

C:\Users\rmrar\AppData\Local\Temp\ipykernel_32088\325617349.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  weather.fillna(method='bfill')

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
1    1/2/2017  35.0   7.0     Sunny
2    1/3/2017  35.0   7.0     Sunny
3    1/4/2017  28.0   2.0      Snow
4    1/5/2017  28.0   2.0      Snow
5    1/6/2017  28.0   2.0      Snow
6    1/7/2017  24.0   5.0      Rain
7    1/8/2017  24.0   5.0      Rain
8    1/9/2017  24.0   7.0      Snow
9   1/10/2017  24.0   7.0      Snow
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

In [12]:
weather.fillna({'temp':23,'wind':8,'condition':'no event'})

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
1    1/2/2017  23.0   8.0  no event
2    1/3/2017  35.0   7.0     Sunny
3    1/4/2017  23.0   8.0  no event
4    1/5/2017  23.0   8.0  no event
5    1/6/2017  28.0   2.0      Snow
6    1/7/2017  23.0   8.0  no event
7    1/8/2017  23.0   5.0      Rain
8    1/9/2017  23.0   8.0  no event
9   1/10/2017  24.0   7.0      Snow
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

In [ ]:
#2.replace
#df.replace(value to be replaced,with what value)

In [13]:
import numpy as np
weather.replace(np.NaN,5)

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
1    1/2/2017   5.0   5.0         5
2    1/3/2017  35.0   7.0     Sunny
3    1/4/2017   5.0   5.0         5
4    1/5/2017   5.0   5.0         5
5    1/6/2017  28.0   2.0      Snow
6    1/7/2017   5.0   5.0         5
7    1/8/2017   5.0   5.0      Rain
8    1/9/2017   5.0   5.0         5
9   1/10/2017  24.0   7.0      Snow
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

In [15]:
weather.replace([np.NaN,'Snow'],[85,'Snows'])

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
1    1/2/2017  85.0  85.0        85
2    1/3/2017  35.0   7.0     Sunny
3    1/4/2017  85.0  85.0        85
4    1/5/2017  85.0  85.0        85
5    1/6/2017  28.0   2.0     Snows
6    1/7/2017  85.0  85.0        85
7    1/8/2017  85.0   5.0      Rain
8    1/9/2017  85.0  85.0        85
9   1/10/2017  24.0   7.0     Snows
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

In [16]:
#3.Drop method-dropna() stands for dropping the null values
weather.dropna()

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
2    1/3/2017  35.0   7.0     Sunny
5    1/6/2017  28.0   2.0      Snow
9   1/10/2017  24.0   7.0      Snow
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

In [17]:
weather.dropna(how='any')

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
2    1/3/2017  35.0   7.0     Sunny
5    1/6/2017  28.0   2.0      Snow
9   1/10/2017  24.0   7.0      Snow
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

In [18]:
weather.dropna(how='all') #it will delete a particular row if all the values in that row are null

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
1    1/2/2017   NaN   NaN       NaN
2    1/3/2017  35.0   7.0     Sunny
3    1/4/2017   NaN   NaN       NaN
4    1/5/2017   NaN   NaN       NaN
5    1/6/2017  28.0   2.0      Snow
6    1/7/2017   NaN   NaN       NaN
7    1/8/2017   NaN   5.0      Rain
8    1/9/2017   NaN   NaN       NaN
9   1/10/2017  24.0   7.0      Snow
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

In [20]:
weather.dropna(thresh=2) #atleast 2 null values should be present in a row

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
2    1/3/2017  35.0   7.0     Sunny
5    1/6/2017  28.0   2.0      Snow
7    1/8/2017   NaN   5.0      Rain
9   1/10/2017  24.0   7.0      Snow
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

In [21]:
weather.dropna(thresh=4)

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
2    1/3/2017  35.0   7.0     Sunny
5    1/6/2017  28.0   2.0      Snow
9   1/10/2017  24.0   7.0      Snow
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny