# Pandas is a powerful Python library used for data manipulation and analysis, particularly well-suited for working with structured data like tables (similar to Excel spreadsheets). 
#### 5 steps of pandas:
1.data reading
2.data inspection
3.data cleaning 
4.data selection and filtering
5.data manipulation

It provides two key data structures:

Series: A one-dimensional labeled array, similar to a list or column in a table.

DataFrame: A two-dimensional labeled data structure, similar to a table with rows and column

## Series

In [3]:
#importing library
import pandas as pd

In [49]:
#creating Series

In [50]:
s1=pd.Series([1,2,3,4,5],name='num',dtype='float')
s1

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
Name: num, dtype: float64

In [51]:
s1=pd.Series([1,2,3,4,5],index=('a','b','c','d','e'),
             name='num',dtype='float')
s1

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
Name: num, dtype: float64

In [1]:
import numpy as np
import pandas as pd
s1=pd.Series(np.linspace(51,60,50),
             name='num',dtype='float')
s1

0     51.000000
1     51.183673
2     51.367347
3     51.551020
4     51.734694
5     51.918367
6     52.102041
7     52.285714
8     52.469388
9     52.653061
10    52.836735
11    53.020408
12    53.204082
13    53.387755
14    53.571429
15    53.755102
16    53.938776
17    54.122449
18    54.306122
19    54.489796
20    54.673469
21    54.857143
22    55.040816
23    55.224490
24    55.408163
25    55.591837
26    55.775510
27    55.959184
28    56.142857
29    56.326531
30    56.510204
31    56.693878
32    56.877551
33    57.061224
34    57.244898
35    57.428571
36    57.612245
37    57.795918
38    57.979592
39    58.163265
40    58.346939
41    58.530612
42    58.714286
43    58.897959
44    59.081633
45    59.265306
46    59.448980
47    59.632653
48    59.816327
49    60.000000
Name: num, dtype: float64

In [3]:
arr1=np.random.randint(70,80,15).reshape(3,5)
arr1

array([[78, 74, 70, 73, 73],
       [79, 74, 79, 71, 79],
       [71, 71, 74, 79, 72]])

In [4]:
res=pd.Series(arr1.reshape(15))
res

0     78
1     74
2     70
3     73
4     73
5     79
6     74
7     79
8     71
9     79
10    71
11    71
12    74
13    79
14    72
dtype: int32

In [2]:
dict1={'name':'neha','age':22,'dep':'ece'}
s1=pd.Series(dict1,name='num')
s1 #in series the key will take the index place

name    neha
age       22
dep      ece
Name: num, dtype: object

In [3]:
# s1['passed_out']=2023
# s1

name          neha
age             22
dep            ece
passed_out    2023
Name: num, dtype: object

In [4]:
# s1['age']

22

## DataFrame

In [3]:
import pandas as pd
data=[['apple',1],['orange',4],['grapes',2],['mango'],
      ['kiwi',5]]
a=pd.DataFrame(data)
a

        0    1
0   apple  1.0
1  orange  4.0
2  grapes  2.0
3   mango  NaN
4    kiwi  5.0

In [4]:
a.columns=['fruits','quantity']
a

   fruits  quantity
0   apple       1.0
1  orange       4.0
2  grapes       2.0
3   mango       NaN
4    kiwi       5.0

In [5]:
a.index=['a','b','c','d','e']
a

   fruits  quantity
a   apple       1.0
b  orange       4.0
c  grapes       2.0
d   mango       NaN
e    kiwi       5.0

In [6]:
a

   fruits  quantity
a   apple       1.0
b  orange       4.0
c  grapes       2.0
d   mango       NaN
e    kiwi       5.0

In [12]:
 a.rename({'a':'ab'},axis=0,inplace=True)
 a

    fruits  quantity
ab   apple       1.0
b   orange       4.0
c   grapes       2.0
d    mango       NaN
e     kiwi       5.0

In [8]:
d=pd.DataFrame(data,columns=['A','B'],index=['A','B','C','D','E']) 
## changing the index
d #keywords in dataframe are - columns,index,shape

        A    B
A   apple  1.0
B  orange  4.0
C  grapes  2.0
D   mango  NaN
E    kiwi  5.0

In [9]:
detail={'name':['abi','poo','baru','shri'],
        'age':[23,22,23,22]}
det=pd.DataFrame(detail)
det#keys-->columns;values-->column values in dataframe

   name  age
0   abi   23
1   poo   22
2  baru   23
3  shri   22

In [10]:
det.index=range(1,5)
det

   name  age
1   abi   23
2   poo   22
3  baru   23
4  shri   22

In [11]:
 det.rename({'age':'ages'},axis=1,inplace=True)
 det

   name  ages
1   abi    23
2   poo    22
3  baru    23
4  shri    22

In [3]:
detail={'person1':{'name':'abi','age':23},
        'person2':{'name':'baru','age':22}}
det=pd.DataFrame(detail)
det#outer keys-->columns;inner keys-->indexes;inner values-->column values

     person1 person2
name     abi    baru
age       23      22

In [86]:
det['person1']

name    abi
age      23
Name: person1, dtype: object

In [4]:
det['person1']['name']

'abi'