In [1]:
import pandas as pd

In [2]:
s=pd.Series([1,2,3,4],name='arun',dtype='float')
s

0    1.0
1    2.0
2    3.0
3    4.0
Name: arun, dtype: float64

In [3]:
s=pd.Series([1,2,3,4],index=('a','b','c','d'),name='num',dtype='float')
s

a    1.0
b    2.0
c    3.0
d    4.0
Name: num, dtype: float64

In [4]:
import numpy as np
import pandas as pd
s=pd.Series(np.linspace(51,60,50),name='num',dtype='float')
s

0     51.000000
1     51.183673
2     51.367347
3     51.551020
4     51.734694
5     51.918367
6     52.102041
7     52.285714
8     52.469388
9     52.653061
10    52.836735
11    53.020408
12    53.204082
13    53.387755
14    53.571429
15    53.755102
16    53.938776
17    54.122449
18    54.306122
19    54.489796
20    54.673469
21    54.857143
22    55.040816
23    55.224490
24    55.408163
25    55.591837
26    55.775510
27    55.959184
28    56.142857
29    56.326531
30    56.510204
31    56.693878
32    56.877551
33    57.061224
34    57.244898
35    57.428571
36    57.612245
37    57.795918
38    57.979592
39    58.163265
40    58.346939
41    58.530612
42    58.714286
43    58.897959
44    59.081633
45    59.265306
46    59.448980
47    59.632653
48    59.816327
49    60.000000
Name: num, dtype: float64

In [6]:
arr1=np.random.randint(70,80,15).reshape(3,5)
arr1

array([[75, 74, 70, 77, 75],
       [71, 73, 78, 77, 70],
       [74, 79, 79, 72, 78]])

In [7]:
pd.Series(arr1.reshape(15,))

0     75
1     74
2     70
3     77
4     75
5     71
6     73
7     78
8     77
9     70
10    74
11    79
12    79
13    72
14    78
dtype: int32

In [8]:
dict1={'name':'neha','age':22,'dep':'ece'}
s=pd.Series(dict1,name='num')
s

name    neha
age       22
dep      ece
Name: num, dtype: object

In [11]:
data=[['apple',1],['orange',4],['grapes',5],['mango']]
r=pd.DataFrame(data)
r

        0    1
0   apple  1.0
1  orange  4.0
2  grapes  5.0
3   mango  NaN

In [12]:
r.columns=['fruits','quantiy']
r

   fruits  quantiy
0   apple      1.0
1  orange      4.0
2  grapes      5.0
3   mango      NaN

In [13]:
r.index=['a','b','c','d']
r

   fruits  quantiy
a   apple      1.0
b  orange      4.0
c  grapes      5.0
d   mango      NaN

In [15]:
r.rename({'a':'ab'},axis=0,inplace=True)
r

    fruits  quantiy
ab   apple      1.0
b   orange      4.0
c   grapes      5.0
d    mango      NaN

In [16]:
d=pd.DataFrame(data,columns=['A','B'],index=['a','b','c','d'])
d

        A    B
a   apple  1.0
b  orange  4.0
c  grapes  5.0
d   mango  NaN

In [17]:
detail={'name':['abi','poo','baru'],'age':[23,24,24]}
d=pd.DataFrame(detail)
d

   name  age
0   abi   23
1   poo   24
2  baru   24

In [19]:
d.rename({'age':'ages'},axis=1,inplace=True)
d

   name  ages
0   abi    23
1   poo    24
2  baru    24

In [20]:
det={'person1':{'name':'abi','age':23},
     'person2':{'name':'anu','age':24}}
de=pd.DataFrame(det)
de

     person1 person2
name     abi     anu
age       23      24

In [21]:
weather=pd.read_csv('wea.csv')
weather

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
1    1/2/2017   NaN   NaN       NaN
2    1/3/2017  35.0   7.0     Sunny
3    1/4/2017   NaN   NaN       NaN
4    1/5/2017   NaN   NaN       NaN
5    1/6/2017  28.0   2.0      Snow
6    1/7/2017   NaN   NaN       NaN
7    1/8/2017   NaN   5.0      Rain
8    1/9/2017   NaN   NaN       NaN
9   1/10/2017  24.0   7.0      Snow
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

In [22]:
weather.isnull()

      day   temp   wind  condition
0   False  False  False      False
1   False   True   True       True
2   False  False  False      False
3   False   True   True       True
4   False   True   True       True
5   False  False  False      False
6   False   True   True       True
7   False   True  False      False
8   False   True   True       True
9   False  False  False      False
10  False  False  False      False
11  False  False  False      False

In [23]:
weather.isnull().sum()

day          0
temp         6
wind         5
condition    5
dtype: int64

In [24]:
weather.isnull().sum().sum()

16

In [25]:
weather.fillna(5)

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
1    1/2/2017   5.0   5.0         5
2    1/3/2017  35.0   7.0     Sunny
3    1/4/2017   5.0   5.0         5
4    1/5/2017   5.0   5.0         5
5    1/6/2017  28.0   2.0      Snow
6    1/7/2017   5.0   5.0         5
7    1/8/2017   5.0   5.0      Rain
8    1/9/2017   5.0   5.0         5
9   1/10/2017  24.0   7.0      Snow
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

In [26]:
weather.fillna(method='ffill')

C:\Users\rmrar\AppData\Local\Temp\ipykernel_3680\589542080.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  weather.fillna(method='ffill')

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
1    1/2/2017  32.0   6.0      Rain
2    1/3/2017  35.0   7.0     Sunny
3    1/4/2017  35.0   7.0     Sunny
4    1/5/2017  35.0   7.0     Sunny
5    1/6/2017  28.0   2.0      Snow
6    1/7/2017  28.0   2.0      Snow
7    1/8/2017  28.0   5.0      Rain
8    1/9/2017  28.0   5.0      Rain
9   1/10/2017  24.0   7.0      Snow
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

In [27]:
weather.fillna(method='ffill',limit=1)

C:\Users\rmrar\AppData\Local\Temp\ipykernel_3680\3365519218.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  weather.fillna(method='ffill',limit=1)

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
1    1/2/2017  32.0   6.0      Rain
2    1/3/2017  35.0   7.0     Sunny
3    1/4/2017  35.0   7.0     Sunny
4    1/5/2017   NaN   NaN       NaN
5    1/6/2017  28.0   2.0      Snow
6    1/7/2017  28.0   2.0      Snow
7    1/8/2017   NaN   5.0      Rain
8    1/9/2017   NaN   5.0      Rain
9   1/10/2017  24.0   7.0      Snow
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

In [28]:
weather.fillna(method='bfill')

C:\Users\rmrar\AppData\Local\Temp\ipykernel_3680\325617349.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  weather.fillna(method='bfill')

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
1    1/2/2017  35.0   7.0     Sunny
2    1/3/2017  35.0   7.0     Sunny
3    1/4/2017  28.0   2.0      Snow
4    1/5/2017  28.0   2.0      Snow
5    1/6/2017  28.0   2.0      Snow
6    1/7/2017  24.0   5.0      Rain
7    1/8/2017  24.0   5.0      Rain
8    1/9/2017  24.0   7.0      Snow
9   1/10/2017  24.0   7.0      Snow
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

In [30]:
weather.fillna({'temp':23,'wind':8,'condition':'no event'})

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
1    1/2/2017  23.0   8.0  no event
2    1/3/2017  35.0   7.0     Sunny
3    1/4/2017  23.0   8.0  no event
4    1/5/2017  23.0   8.0  no event
5    1/6/2017  28.0   2.0      Snow
6    1/7/2017  23.0   8.0  no event
7    1/8/2017  23.0   5.0      Rain
8    1/9/2017  23.0   8.0  no event
9   1/10/2017  24.0   7.0      Snow
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

In [32]:
weather.replace(np.NaN,5)

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
1    1/2/2017   5.0   5.0         5
2    1/3/2017  35.0   7.0     Sunny
3    1/4/2017   5.0   5.0         5
4    1/5/2017   5.0   5.0         5
5    1/6/2017  28.0   2.0      Snow
6    1/7/2017   5.0   5.0         5
7    1/8/2017   5.0   5.0      Rain
8    1/9/2017   5.0   5.0         5
9   1/10/2017  24.0   7.0      Snow
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

In [33]:
weather.replace([np.NaN,'Snow'],[85,'Snows'])

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
1    1/2/2017  85.0  85.0        85
2    1/3/2017  35.0   7.0     Sunny
3    1/4/2017  85.0  85.0        85
4    1/5/2017  85.0  85.0        85
5    1/6/2017  28.0   2.0     Snows
6    1/7/2017  85.0  85.0        85
7    1/8/2017  85.0   5.0      Rain
8    1/9/2017  85.0  85.0        85
9   1/10/2017  24.0   7.0     Snows
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

In [34]:
weather.dropna()

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
2    1/3/2017  35.0   7.0     Sunny
5    1/6/2017  28.0   2.0      Snow
9   1/10/2017  24.0   7.0      Snow
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

In [35]:
weather.dropna(how='any')

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
2    1/3/2017  35.0   7.0     Sunny
5    1/6/2017  28.0   2.0      Snow
9   1/10/2017  24.0   7.0      Snow
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

In [37]:
weather.dropna(how='all')

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
1    1/2/2017   NaN   NaN       NaN
2    1/3/2017  35.0   7.0     Sunny
3    1/4/2017   NaN   NaN       NaN
4    1/5/2017   NaN   NaN       NaN
5    1/6/2017  28.0   2.0      Snow
6    1/7/2017   NaN   NaN       NaN
7    1/8/2017   NaN   5.0      Rain
8    1/9/2017   NaN   NaN       NaN
9   1/10/2017  24.0   7.0      Snow
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

In [38]:
weather.dropna(thresh=2)

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
2    1/3/2017  35.0   7.0     Sunny
5    1/6/2017  28.0   2.0      Snow
7    1/8/2017   NaN   5.0      Rain
9   1/10/2017  24.0   7.0      Snow
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

In [39]:
weather.dropna(thresh=4)

          day  temp  wind condition
0    1/1/2017  32.0   6.0      Rain
2    1/3/2017  35.0   7.0     Sunny
5    1/6/2017  28.0   2.0      Snow
9   1/10/2017  24.0   7.0      Snow
10  1/11/2017  32.0   4.0      Rain
11  1/12/2017  31.0   2.0     Sunny

In [41]:
titanic=pd.read_csv('titanic.csv')
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [42]:
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [43]:
titanic.index

RangeIndex(start=0, stop=891, step=1)

In [44]:
titanic.shape

(891, 12)

In [45]:
titanic.shape[0]

891

In [46]:
rows,columns=titanic.shape
print(rows)

891

In [47]:
titanic.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [48]:
titanic.tail(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [49]:
titanic.sample()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
252,253,0,1,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.55,C87,S

In [50]:
titanic.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
165,166,1,3,"Goldsmith, Master. Frank John William ""Frankie""",male,9.0,0,2,363291,20.5250,NaN,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
34,35,0,1,"Meyer, Mr. Edgar Joseph",male,28.0,1,0,PC 17604,82.1708,NaN,C
241,242,1,3,"Murphy, Miss. Katherine ""Kate""",female,NaN,1,0,367230,15.5000,NaN,Q

In [51]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [53]:
titanic.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [54]:
titanic.describe(include='O')

                           Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

In [55]:
titanic[['Name']]

                                                  Name
0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
..                                                 ...
886                              Montvila, Rev. Juozas
887                       Graham, Miss. Margaret Edith
888           Johnston, Miss. Catherine Helen "Carrie"
889                              Behr, Mr. Karl Howell
890                                Dooley, Mr. Patrick

[891 rows x 1 columns]

In [56]:
titanic['Sex'].unique()

array(['male', 'female'], dtype=object)

In [57]:
titanic['Sex'].nunique()

2

In [58]:
titanic['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [59]:
titanic['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [60]:
titanic['Embarked'].nunique()

3

In [61]:
titanic['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [63]:
titanic.select_dtypes(include='object').columns

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [64]:
titanic.select_dtypes(include=['int','float']).columns

Index(['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [65]:
titanic.duplicated().sum()

0

In [66]:
titanic.drop_duplicates(inplace=True)

In [67]:
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [68]:
titanic[titanic['Pclass']==2]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
...,...,...,...,...,...,...,...,...,...,...,...,...
866,867,1,2,"Duran y More, Miss. Asuncion",female,27.0,1,0,SC/PARIS 2149,13.8583,NaN,C
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S

In [69]:
titanic[titanic['Pclass']==2][['Name','Sex']]

                                             Name     Sex
9             Nasser, Mrs. Nicholas (Adele Achem)  female
15               Hewlett, Mrs. (Mary D Kingcome)   female
17                   Williams, Mr. Charles Eugene    male
20                           Fynney, Mr. Joseph J    male
21                          Beesley, Mr. Lawrence    male
..                                            ...     ...
866                  Duran y More, Miss. Asuncion  female
874         Abelson, Mrs. Samuel (Hannah Wizosky)  female
880  Shelley, Mrs. William (Imanita Parrish Hall)  female
883                 Banfield, Mr. Frederick James    male
886                         Montvila, Rev. Juozas    male

[184 rows x 2 columns]

In [70]:
titanic.rename({'Sex':'Gender'},axis=1,inplace=True)

In [71]:
titanic[(titanic['Gender']=='male')&(titanic['Survived']==1)&(titanic['Pclass']==2)*(titanic['Age']>60)]

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
570,571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5,NaN,S

In [72]:
titanic.iloc[70:81,2:5]

    Pclass                           Name  Gender
70       2     Jenkin, Mr. Stephen Curnow    male
71       3     Goodwin, Miss. Lillian Amy  female
72       2           Hood, Mr. Ambrose Jr    male
73       3    Chronopoulos, Mr. Apostolos    male
74       3                  Bing, Mr. Lee    male
75       3        Moen, Mr. Sigurd Hansen    male
76       3              Staneff, Mr. Ivan    male
77       3       Moutal, Mr. Rahamin Haim    male
78       2  Caldwell, Master. Alden Gates    male
79       3       Dowdell, Miss. Elizabeth  female
80       3           Waelens, Mr. Achille    male

In [73]:
titanic.iloc[:11,[1,2,4]]

    Survived  Pclass  Gender
0          0       3    male
1          1       1  female
2          1       3  female
3          1       1  female
4          0       3    male
5          0       3    male
6          0       1    male
7          0       3    male
8          1       3  female
9          1       2  female
10         1       3  female

In [74]:
titanic.loc[:10,['Survived','Pclass']]

    Survived  Pclass
0          0       3
1          1       1
2          1       3
3          1       1
4          0       3
5          0       3
6          0       1
7          0       3
8          1       3
9          1       2
10         1       3

In [75]:
titanic.sort_values(by='Age',ascending=False)

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [77]:
g=titanic.groupby('Gender')
g

In [78]:
list(g)

[('female',
       PassengerId  Survived  Pclass  \
  1              2         1       1
  2              3         1       3
  3              4         1       1
  8              9         1       3
  9             10         1       2
  ..           ...       ...     ...
  880          881         1       2
  882          883         0       3
  885          886         0       3
  887          888         1       1
  888          889         0       3

                                                    Name  Gender   Age  SibSp  \
  1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
  2                               Heikkinen, Miss. Laina  female  26.0      0
  3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
  8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
  9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1
  ..                                                 ...     ...   ...    ...
  880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0
  882                       Dahlberg, Miss. Gerda Ulrika  female  22.0      0
  885               Rice, Mrs. William (Margaret Norton)  female  39.0      0
  887                       Graham, Miss. Margaret Edith  female  19.0      0
  888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1

       Parch            Ticket     Fare Cabin Embarked
  1        0          PC 17599  71.2833   C85        C
  2        0  STON/O2. 3101282   7.9250   NaN        S
  3        0            113803  53.1000  C123        S
  8        2            347742  11.1333   NaN        S
  9        0            237736  30.0708   NaN        C
  ..     ...               ...      ...   ...      ...
  880      1            230433  26.0000   NaN        S
  882      0              7552  10.5167   NaN        S
  885      5            382652  29.1250   NaN        Q
  887      0            112053  30.0000   B42        S
  888      2        W./C. 6607  23.4500   NaN        S

  [314 rows x 12 columns]),
 ('male',
       PassengerId  Survived  Pclass                            Name Gender  \
  0              1         0       3         Braund, Mr. Owen Harris   male
  4              5         0       3        Allen, Mr. William Henry   male
  5              6         0       3                Moran, Mr. James   male
  6              7         0       1         McCarthy, Mr. Timothy J   male
  7              8         0       3  Palsson, Master. Gosta Leonard   male
  ..           ...       ...     ...                             ...    ...
  883          884         0       2   Banfield, Mr. Frederick James   male
  884          885         0       3          Sutehall, Mr. Henry Jr   male
  886          887         0       2           Montvila, Rev. Juozas   male
  889          890         1       1           Behr, Mr. Karl Howell   male
  890          891         0       3             Dooley, Mr. Patrick   male

        Age  SibSp  Parch            Ticket     Fare Cabin Embarked
  0    22.0      1      0         A/5 21171   7.2500   NaN        S
  4    35.0      0      0            373450   8.0500   NaN        S
  5     NaN      0      0            330877   8.4583   NaN        Q
  6    54.0      0      0             17463  51.8625   E46        S
  7     2.0      3      1            349909  21.0750   NaN        S
  ..    ...    ...    ...               ...      ...   ...      ...
  883  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S
  884  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S
  886  27.0      0      0            211536  13.0000   NaN        S
  889  26.0      0      0            111369  30.0000  C148        C
  890  32.0      0      0            370376   7.7500   NaN        Q

  [577 rows x 12 columns])]

In [79]:
for gender,data in g:
    print(gender)
    print(data)

female
     PassengerId  Survived  Pclass  \
1              2         1       1
2              3         1       3
3              4         1       1
8              9         1       3
9             10         1       2
..           ...       ...     ...
880          881         1       2
882          883         0       3
885          886         0       3
887          888         1       1
888          889         0       3

                                                  Name  Gender   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1
..                                                 ...     ...   ...    ...
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0
882                       Dahlberg, Miss. Gerda Ulrika  female  22.0      0
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1

     Parch            Ticket     Fare Cabin Embarked
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
8        2            347742  11.1333   NaN        S
9        0            237736  30.0708   NaN        C
..     ...               ...      ...   ...      ...
880      1            230433  26.0000   NaN        S
882      0              7552  10.5167   NaN        S
885      5            382652  29.1250   NaN        Q
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S

[314 rows x 12 columns]
male
     PassengerId  Survived  Pclass                            Name Gender  \
0              1         0       3         Braund, Mr. Owen Harris   male
4              5         0       3        Allen, Mr. William Henry   male
5              6         0       3                Moran, Mr. James   male
6              7         0       1         McCarthy, Mr. Timothy J   male
7              8         0       3  Palsson, Master. Gosta Leonard   male
..           ...       ...     ...                             ...    ...
883          884         0       2   Banfield, Mr. Frederick James   male
884          885         0       3          Sutehall, Mr. Henry Jr   male
886          887         0       2           Montvila, Rev. Juozas   male
889          890         1       1           Behr, Mr. Karl Howell   male
890          891         0       3             Dooley, Mr. Patrick   male

      Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0    22.0      1      0         A/5 21171   7.2500   NaN        S
4    35.0      0      0            373450   8.0500   NaN        S
5     NaN      0      0            330877   8.4583   NaN        Q
6    54.0      0      0             17463  51.8625   E46        S
7     2.0      3      1            349909  21.0750   NaN        S
..    ...    ...    ...               ...      ...   ...      ...
883  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S
884  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S
886  27.0      0      0            211536  13.0000   NaN        S
889  26.0      0      0            111369  30.0000  C148        C
890  32.0      0      0            370376   7.7500   NaN        Q

[577 rows x 12 columns]

In [80]:
g.get_group('male')

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [81]:
titanic.groupby('Gender').count()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Gender,,,,,,,,,,,
female,314,314,314,314,261,314,314,314,314,97,312
male,577,577,577,577,453,577,577,577,577,107,577

In [82]:
titanic.groupby('Gender')['Age'].count()

Gender
female    261
male      453
Name: Age, dtype: int64

In [83]:
res=titanic.groupby('Gender')[['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare']].agg(['mean','count','min'])

In [84]:
res

       PassengerId            Survived              Pclass            \
              mean count min      mean count min      mean count min
Gender
female  431.028662   314   2  0.742038   314   0  2.159236   314   1
male    454.147314   577   1  0.188908   577   0  2.389948   577   1

              Age  ...           SibSp               Parch            \
             mean  ...   min      mean count min      mean count min
Gender             ...
female  27.915709  ...  0.75  0.694268   314   0  0.649682   314   0
male    30.726645  ...  0.42  0.429809   577   0  0.235702   577   0

             Fare
             mean count   min
Gender
female  44.479818   314  6.75
male    25.523893   577  0.00

[2 rows x 21 columns]

In [85]:
res=titanic.groupby('Gender').agg({'Age':['mean','max','count'],'Fare':['mean','max']})

In [86]:
res

              Age                   Fare
             mean   max count       mean       max
Gender
female  27.915709  63.0   261  44.479818  512.3292
male    30.726645  80.0   453  25.523893  512.3292

In [87]:
titanic.groupby(['Gender','Survived'])['Age'].mean()

Gender  Survived
female  0           25.046875
        1           28.847716
male    0           31.618056
        1           27.276022
Name: Age, dtype: float64

In [88]:
titanic.set_index(['PassengerId'])

,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [89]:
def classdiv(class1):
    if class1==1:
        return 'business1'
    elif class1==2:
        return 'business2'
    else:
        return 'economis'

In [90]:
titanic['class']=titanic['Pclass'].apply(classdiv)

In [91]:
titanic

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,class
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,economis
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,business1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,economis
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,business1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,economis
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,business2
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,business1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,economis
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,business1
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,economis

In [92]:
def classdiv1(pclass,fare):
    if pclass==1 and fare>30:
        return 'luxury'
    elif pclass==2 and fare>20:
        return 'premium'
    elif pclass==3:
        return 'economy'
    else:
        return 'basic'

In [94]:
titanic['category1']=titanic.apply(lambda row:classdiv1(row['Pclass'],row['Fare']),axis=1)
titanic

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,class,category1
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,economis,economy
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,business1,luxury
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,economis,economy
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,business1,luxury
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,economis,economy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,business2,basic
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,business1,basic
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,economis,economy
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,business1,basic
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,economis,economy

In [ ]:
#pd.set_option('display.max_rows',None)